version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ecoride_app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ecoride
      - MYSQL_USER=ecoride_user
      - MYSQL_PASSWORD=ecoride_pass
      - AUTH_SECRET=change_this_secret
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html/src:cached
      - ./api:/var/www/html/api:cached
    networks:
      - ecoride-net
  mysql:
    image: mysql:8.0
    container_name: ecoride_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: ecoride_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "3306:3306"
    networks:
      - ecoride-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecoride_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - ecoride-net
volumes:
  db_data:
networks:
  ecoride-net:
    driver: bridge
